---
title: "Working hours for Hogeschool Rotterdam"
format: 
    typst: 
        template-partials: 
            - typst-show.typ
            - typst-template.typ
echo: False 
---







```{python}
# | tags: [parameters]

data_path = "path/to/excell/file"
hourly_rate = 0  # euro
```

```{python}
from pathlib import Path
from analytics import prepare_data

hours_data = prepare_data(Path(data_path))
```



```{=typst}
#horizontal_line()
```

**lecturer/student project team coach**  
As part of the *minor in Data science* , offered by the 'instituut voor Communicatie, Media en Informatietechnologie (CMI)', I assisted in their minor-long *data science project*. After been given a choice of several initial data sets, the students decided on their own research questions, cleaned and enriched their data (from outside sources), conducted literature research into their chosen topic, and trained/tested their Machine-Learning/data science based solution. My role is to act as a *team coach* for three of the teams: Guiding them throughout this journey into what for many is their first bit of research experience. 
 
```{=typst}
#horizontal_line()
```

## Breakdown
Details of hours spent. 

#### What activities did I perform? 
<div style="background-color: #F8F8F8;">
:::{layout-ncol="2"}
```{python}
from analytics import plot_pie_chart_activities

plot_pie_chart_activities(hours_data)
```
```{python}
from analytics import plot_monthly_hours_breakdown

plot_monthly_hours_breakdown(hours_data)
```
:::
</div>

#### When did I perform them? 
<div style="background-color: #F8F8F8;">
:::{layout-ncol="2"}

```{python}
from analytics import plot_daily_hours

plot_daily_hours(hours_data)
```

```{python}
from analytics import plot_pie_chart_days

plot_pie_chart_days(hours_data)
```
:::
</div>

#### How much to declare? 
<div style="background-color: #F8F8F8;">
:::{layout-ncol="2"}

```{python}
from analytics import bar_chart_monthly_incomes

bar_chart_monthly_incomes(hours_data, hourly_rate)
```




:::
</div>

```{python}
# | output: asis
from analytics import create_html_monthly_incomes

formatting = {"size": 22, "bold": True, "italic": True}
html = create_html_monthly_incomes(hours_data, hourly_rate, formatting)
print(html)
```